// File generated by FlutterFire CLI - placeholder for FCM
// Replace with `flutterfire configure` output. Do NOT commit google-services.json with secrets.
// For ProcureFlow: after Firebase Console project creation, run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=YOUR_PROJECT_ID --platforms=android,ios
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions not configured for web - run flutterfire configure');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Placeholder - will be overridden by google-services.json at build time
        // Provide minimal stub to allow compilation without real config; real FCM will init via native google-services.json
        return const FirebaseOptions(
          apiKey: 'placeholder-api-key',
          appId: '1:000000000000:android:0000000000000000000000',
          messagingSenderId: '000000000000',
          projectId: 'procureflow-pending',
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: 'placeholder-ios-key',
          appId: '1:000000000000:ios:0000000000000000000000',
          messagingSenderId: '000000000000',
          projectId: 'procureflow-pending',
          iosBundleId: 'com.procureflow.procureflow',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions not configured for $defaultTargetPlatform');
    }
  }
}
