// File generated by FlutterFire CLI - placeholder for FCM
// Replace with `flutterfire configure` output. Do NOT commit google-services.json with secrets.
// For ProcureFlow: after Firebase Console project creation, run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=YOUR_PROJECT_ID --platforms=android,ios
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions not configured for web - run flutterfire configure');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'AIzaSyByger6P_iMUcoa1KsUfsqjuExvd7g3kcQ',
          appId: '1:327626589824:android:e4c9d5e25a7f58e3ac8865',
          messagingSenderId: '327626589824',
          projectId: 'procureflow-bf2d3',
          storageBucket: 'procureflow-bf2d3.firebasestorage.app',
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: 'placeholder-ios-key',
          appId: '1:000000000000:ios:0000000000000000000000',
          messagingSenderId: '000000000000',
          projectId: 'procureflow-pending',
          iosBundleId: 'com.procureflow.procureflow',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions not configured for $defaultTargetPlatform');
    }
  }
}
